---
title: Overview 
slide-format: revealjs
css: styles.css
execute:
  echo: false
---

Foods like milk are complex mixtures of many different components. For
product applications it is often desirable to `fractionate` mixtures into their
components so that they can ultimately be used as ingredients.
For both their *bio-functional* (e.g., nutrition) and *techno-functional* (e.g.,
stabilisation) attributes proteins are an attractive target for many separation
processes. 

<div>
```{=html}
<iframe class="video-embed" src=./vids/ObjectsSurround.mp4></iframe>
```

It has been common practice in the dairy industry for many years to fractionate caseins from liquid whey and, more recently, to further
fractionate liquid whey into whey proteins.
In the lecture and practical that accompany these notes several different methods for fractionating dairy proteins — one `chemical`, one
`biochemical` and one `physical` — will be discussed. The chemical process exploits the fact that casein micelles coagulate in acidic conditions, the biochemical
process takes advantage of the tendency of casein to coagulate in the presence
of rennet, while the physical process exploits the relative differences in
size between molecules in milk and whey.

::: {.callout-note}

**Fractionation** is the technical term often used for the separation of one component relative to other components.

This is distinct from **concentration**, which typically means concentration of **all** (solid) components by removal of water.

:::

## Slides

Slides for this practical are embedded below — you can interact with them easily on your phone, tablet or computer.

<div>
```{=html}
<iframe class="slide-deck" src="slides/one/"></iframe>
```
</div>

:::{.callout-tip}
## Full-screen slides — recommended, especially for mobile

[📽️ Direct link to slides for this lecture](slides/one/)

After clicking on a slide you can also hit <kbd>f</kbd> to show the slides in fullscreen.

:::
