---
title: "Protein Fractionation"
author: "Dr Shane Crowley"
subtitle: "Practical Session"
format:
  revealjs: 
    theme: dark
    slide-number: true
    chalkboard:
        theme: "whiteboard"
        grid: { color: 'rgb(50,50,10,0.1)', distance: 30, width: 1}
    buttons: true
    controls: true
    preview-links: true
    # logo: images/quarto.png
    footer: Food Analysis & Processing 
search: false
---

> Fractionation: dividing a whole into a sub-set of its component parts
<video src="../../vids/ObjectsSurround.mp4" controls="true" style="width: 100%; height: 100%;" data-preload></iframe>

::: footer

:::       

---

<section data-auto-animate>
    <h3>Sequence</h3>
    <ol>
        <li style="color:rgb(223, 193, 27)">Reviewing casein and whey protein chemistry</li>   
    </ol>
</section>

<section data-auto-animate>
    <h3>Sequence</h3>
    <ol>
        <li style="opacity: 0.5;">Reviewing casein and whey protein chemistry</li>
        <li style="color:rgb(223, 193, 27)">Making acid CN, rennet CN & sodium caseinate</li>
    </ol>
</section>

<section data-auto-animate>
    <h3>Sequence</h3>
    <ol>
        <li style="opacity: 0.5;">Reviewing casein and whey protein chemistry</li>
        <li style="opacity: 0.5;">Making acid CN, rennet CN & sodium caseinate</li>
        <li style="color:rgb(223, 193, 27)">Visualising a filtration process</li>
    </ol>
</section>

<section data-auto-animate>
    <h3 style="opacity: 0.0;">Sequence</h3>
    <ol>
        <li style="opacity: 0.0;">Reviewing casein and whey protein chemistry</li>
        <li style="opacity: 0.0;">Making acid CN, rennet CN & sodium caseinate</li>
        <li style="opacity: 0.0;">Visualising a filtration process</li>
    </ol>
</section>

---

## Approximate Milk Composition

<br>

|***Component***|***Level(%)***|***Properties***              |
|:--------|:--------:|---------------------------------:|
|Water    |90    |Solvent, growth medium               |
|Lactose  |5     |Sweetness, calorie source                   |
|Protein  |3.5   |Surfactant, *aa* source  |
|Ash      |1.0   |Mineral source, saltiness                  |
||

---

<br>
<br>

:::{.r-fit-text}
🥛 + 🍋 = ❓
:::

---

<video src="../../vids/iso_elec_c1.mp4" controls="true" style="width: 100%; height: 100%;" data-preload></video>

---

<section data-auto-animate>
    <h3 style="color: darkorange;">Making acid casein</h3>
    <ul>
      <li>Milk</li>
      <li>Lemon juice</li>
      <li>Water</li>
    </ul>
  </section>

<section data-auto-animate>
    <h3 style="color: darkorange;">...and sodium caseinate</h3>
    <ul>
      <li>Milk</li>
      <li>Lemon juice</li>
      <li>Baking soda</li>
      <li>Water</li>
</section>

<section data-auto-animate>
    <h3 style="color: darkorange;">...and sodium caseinate</h3>
    <ul>
      <li>Milk</li>
      <li><strike>Lemon juice</strike> 👉 HCl </li>
      <li><strike>Baking soda</strike> 👉 NaOH</li>
      <li>Water</li>
</section>

---

<video data-autoplay src="https://github.com/edibotopic/proFracLab/raw/master/vids/ACN_pfd_c1.mp4" controls="true" data-preload style="width:100%; height:100%"></video>

---

<h3 style="color: darkorange;">Rennet Casein</h3>
<ul>
    <li>Many <b>common steps</b> with acid CN production</li>
    <br>
    <li><u>But</u>, coagulation is <b>enzymatic</b> not isolectric</li>
    <br>
    <li>There is <b>no acidification</b> so little change in [CCP]</li>
    <br>
    <li>Ingredient is used in <b>analogue cheese</b></li>

---

<section data-transition="slide" data-background="#4B226D" data-background-transition="zoom">
<h2 style="color: #FE82E5;">Cross-flow Filtration</h2>
<p>
    To make acid or rennet casein the proteins must be <i style="color: #EC71D2;">(bio)chemically modified</i> before filtration.
    If smaller-pore filters are used it is possible to recover proteins without causing
    these modifications. However, to push liquid through these filters greater <i style="color: #EC71D2;">pressure</i>
    and <i style="color: #EC71D2;">turbulence</i> is required.
</p>
<p>
    A demo of the UCC equipment by <i>PhD student <b>Tom France</b>
    can be found on the UCC <a href="https://www.ucc.ie/en/canvas/">Canvas</a> page</i>
</p>
</section>

---
    
<video data-autoplay src="https://github.com/edibotopic/proFracLab/raw/master/vids/pro_frac_vid_c1.mp4" controls="true" style="width: 100%; height: 100%;" data-preload></video>

---

<section data-background-iframe="https://sketchfab.com/models/e65e9fd49e8b47f7a2a117d3135e7297/embed" data-background-interactive>
</section>
