---
title: Note on Whey Streams 
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---

Although the focus in this practical is on the casein ingredients developed by
precipitation, it should be remembered that each process generates a whey
stream. 
The properties of the whey stream is fundamentally shaped by the specific casein production process used.
As acidification almost completely solubilises the colloidal calcium phosphate (`CCP`) associated with the casein micelles during acid casein manufacture acid whey is far more enriched in minerals than rennet whey, as the latter is not subject to acidification, keeping the CCP mostly intact.
Logically, it follows that the rennet casein itself is more heavily mineralised than the acid casein.
The presence of additional minerals in the acid whey often creates problems during the manufacture of other ingredients (e.g., whey
powders, WPCs) as the calcium phosphate in particular can become insoluble during whey processing.
However, these minerals can also be recovered
as a valuable ingredient known simply as ”milk minerals”.

[📚 Book chapter on milk minerals as an ingredient (accessible with UCC student account)](https://www.sciencedirect.com/science/article/pii/B9780128187661001112)

A final remark should be made about the fate of the fragments of κ-
casein that are liberated during renneting (though not acidification). These fragments are known as ”glycomacropeptide” or ”`GMP`” for short.
This name simply means a big (macro) string of amino acids (peptide) that is glycosylated (glyco).
Rennet whey is rich in GMP, and some companies fractionate this material to create nutritional products for the treatment of phenylketonuria (`PKU`), a condition in which afflicted individuals have issues
consuming protein in the diet, more specifically foods containing the amino acid phenylalanine (which GMP is very low in).

[📚 Free article on the use manufacture and use of GMP in nutritional management of PKU](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3632067/
)

When you are thinking about these materials you should always think of
what properties are being exploited to produce them, how the process used
impacts the different streams that are generated, and how some of these
changes can form the basis of further innovation.
